name: Bot
run-name: 🤖 beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: ./.github/actions/bot
