name: Build AMI

on:
  pull_request:
    branches: [ master ]
    types:
    - "opened"
    - "synchronize"
    - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read        
    strategy:
      matrix:
        include:
          - K8S_VERSION: "1.18"
          - K8S_VERSION: "1.19"
          - K8S_VERSION: "1.20"
          - K8S_VERSION: "1.21"
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::380217597436:role/github-actions-role-Role-1SS1G46UVILIE      
      - name: ${{ matrix.K8S_VERSION }}
        run: make ${{ matrix.K8S_VERSION }}
