name: Build AMI

on:
  pull_request:
    branches: [ master ]
    types:
    - "opened"
    - "synchronize"
    - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - K8S_VERSION: "1.18"
          - K8S_VERSION: "1.19"
          - K8S_VERSION: "1.20"
          - K8S_VERSION: "1.21"
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master
      - uses: actions/checkout@v2
      - name: ${{ matrix.K8S_VERSION }}
        run: make ${{ matrix.K8S_VERSION }}
