name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - run: make lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
  build-pr:
    if: github.event.name == 'pull_request'
    needs: unit-test
    strategy:
      matrix:
        k8s_version: ['1.20', '1.21', '1.22', '1.23']
    uses: ./.github/workflows/build.yml
    with:
      k8s_version: ${{ matrix.K8S_VERSION }}
      build_id: ${{ matrix.K8S_VERSION }}-$(git rev-parse --short $GITHUB_SHA)
  build-head:
    needs: unit-test
    strategy:
      matrix:
        k8s_version: ['1.20', '1.21', '1.22', '1.23']
    uses: ./.github/workflows/build.yml
    with:
      k8s_version: ${{ matrix.K8S_VERSION }}
      build_id: ${{ matrix.K8S_VERSION }}-$(git rev-parse --short $GITHUB_SHA)-pr-${{ github.event.pull_request.number }}