name: '[CI] Entrypoint'
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.variables.outputs.sha_short }}    
    steps:
    - id: variables
      run: echo "sha_short=$(echo ${{ github.sha }} | rev | cut -c-7 | rev)" >> $GITHUB_OUTPUT    
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - run: make lint
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test  
  version-workflow:
    name: ${{ matrix.k8s_version }}
    needs: unit-test
    strategy:
      matrix:
        k8s_version: ['1.20', '1.21', '1.22', '1.23', '1.24']
    uses: ./.github/workflows/ci-build.yml
    with:
      k8s_version: ${{ matrix.k8s_version }}
      build_id: ${{ github.event_name }}-${{ needs.setup.outputs.sha_short }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    secrets: inherit
