name: '[Janitor] Entrypoint'
on:
  schedule:
    # hourly at the top of the hour
    - cron: '0 * * * *'
jobs:
  cluster-sweeper:
    uses: ./.github/workflows/janitor-cluster-sweeper.yml
    secrets: inherit
    with:
      # 6 hours
      max_age_seconds: 21600