name: Require pull request labels

on:
  pull_request:
    branches: [ master ]
    types:
    - "labeled"
    - "unlabeled"
    - "opened"
    - "reopened"
    - "synchronize"

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          valid-labels: 'buildable'
          pull-request-number: '${{ github.event.pull_request.number }}'
          disable-reviews: true
