name: '[Sync] Push to CodeCommit'

on:
  push:
    branches:    
      - 'master'

jobs:
  mirror:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - run: git config credential.helper '!aws codecommit credential-helper $@'
      - run: git config credential.UseHttpPath true
      - run: git remote add mirror ${{ secrets.AWS_CODECOMMIT_REPO_URL }}
      - run: git push mirror
